controller_list:
  - name: csda10f/csda10f_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_left_joint_1_s,
             arm_left_joint_2_l,
             arm_left_joint_3_e,
             arm_left_joint_4_u,
             arm_left_joint_5_r,
             arm_left_joint_6_b,
             arm_left_joint_7_t,
             arm_right_joint_1_s,
             arm_right_joint_2_l,
             arm_right_joint_3_e,
             arm_right_joint_4_u,
             arm_right_joint_5_r,
             arm_right_joint_6_b,
             arm_right_joint_7_t,
             torso_joint_b1]

  - name: csda10f/left_arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_left_joint_1_s,
             arm_left_joint_2_l,
             arm_left_joint_3_e,
             arm_left_joint_4_u,
             arm_left_joint_5_r,
             arm_left_joint_6_b,
             arm_left_joint_7_t]

  - name: csda10f/right_arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_right_joint_1_s,
             arm_right_joint_2_l,
             arm_right_joint_3_e,
             arm_right_joint_4_u,
             arm_right_joint_5_r,
             arm_right_joint_6_b,
             arm_right_joint_7_t]

  - name: csda10f/torso_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [torso_joint_b1]

  # - name: csda10f/csda10f_b2_controller
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints: [torso_joint_b2]
  #
