controller_list:
  - name: fake_csda10f_controller
    joints:
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
      - arm_right_joint_1_s
      - arm_right_joint_2_l
      - arm_right_joint_3_e
      - arm_right_joint_4_u
      - arm_right_joint_5_r
      - arm_right_joint_6_b
      - arm_right_joint_7_t
      - torso_joint_b1
  - name: fake_left_arm_controller
    joints:
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
  - name: fake_right_arm_controller
    joints:
      - arm_right_joint_1_s
      - arm_right_joint_2_l
      - arm_right_joint_3_e
      - arm_right_joint_4_u
      - arm_right_joint_5_r
      - arm_right_joint_6_b
      - arm_right_joint_7_t
  - name: fake_camera_controller
    joints:
      - camera_joint_y
      - camera_joint_z
  - name: fake_base_controller
    joints:
      - virtual_joint
      - left_wheel_joint
      - right_wheel_joint
  - name: fake_torso_controller
    joints:
      - torso_joint_b1
  - name: fake_right_hand_controller
    joints:
      - right_base_hand_big_thumb_1
      - right_base_hand_big_thumb_2
      - right_base_hand_big_thumb_3
      - right_hand_finger_1_joint
      - right_hand_finger_shizhimid_joint
      - right_hand_finger_shizhitop_joint
      - right_hand_finger_2_joint
      - right_hand_finger_zhongzhimid_joint
      - right_hand_finger_zhongzhitop_joint
      - right_hand_finger_3_joint
      - right_hand_finger_wumingzhimid_joint
      - right_hand_finger_wumingzhitop_joint
      - right_hand_finger_4_joint
      - right_hand_finger_xiaozhimid_joint
      - right_hand_finger_xiaozhitop_joint
  - name: fake_left_hand_controller
    joints:
      - left_base_hand_big_thumb_1
      - left_base_hand_big_thumb_2
      - left_base_hand_big_thumb_3
      - left_hand_finger_1_joint
      - left_hand_finger_shizhimid_joint
      - left_hand_finger_shizhitop_joint
      - left_hand_finger_2_joint
      - left_hand_finger_zhongzhimid_joint
      - left_hand_finger_zhongzhitop_joint
      - left_hand_finger_3_joint
      - left_hand_finger_wumingzhimid_joint
      - left_hand_finger_wumingzhitop_joint
      - left_hand_finger_4_joint
      - left_hand_finger_xiaozhimid_joint
      - left_hand_finger_xiaozhitop_joint
