<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:macro name="right_hand">

<!-- Defining the colors used in this robot -->
    <!-- <material name="white">
        <color rgba="1 1 1 0"/>
    </material>

    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>

    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>

    <material name="black">
        <color rgba="0.75 0.75 0.75 1"/>
    </material> -->

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- Main body length, width, height and mass -->
    <xacro:property name="base_link_x" value="0.11" />
    <xacro:property name="base_link_y" value="0.10"/>
    <xacro:property name="base_link_z" value="0.032"/>
    <xacro:property name="base_link_mass" value="1.0"/>
    <!-- Caster radius and mass -->
    <xacro:property name="finger_width"                   value="0.022" />
    <xacro:property name="finger_thickness"               value="0.011" />
    <xacro:property name="finger_down"                    value="0.0551" />
    <xacro:property name="finger_mid"                     value="0.03775"/>
    <xacro:property name="finger_top"                     value="0.02294" />
    <xacro:property name="finger_down"                    value="0.0551" />
    <xacro:property name="finger_zhongzhi_mid"            value="0.04905" />
    <xacro:property name="finger_zhongzhi_top"            value="0.027489"/>
    <xacro:property name="finger_down_mass"               value="0.04217"/>
    <xacro:property name="finger_mid_mass"                value="0.03053"/>
    <xacro:property name="finger_top_mass"                value="0.02548"/>
    <xacro:property name="finger_zhongzhi_mid_mass"       value="0.03816"/>
    <xacro:property name="finger_zhongzhi_top_mass"       value="0.02386"/>

    <!-- Macro for inertia matrix -->
    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                iyy="${2*m*r*r/5}" iyz="0"
                izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertial_matrix" params="m w h d">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
                iyy="${m*(w*w+d*d)/12}" iyz = "0"
                izz="${m*(w*w+h*h)/12}" />
        </inertial>
    </xacro:macro>

      <!-- Define finger -->
    <xacro:macro name="right_hand_finger" params="parent number prefix_1 prefix_2 prefix_3 joint_x_loc joint_y_loc joint_z_loc joint_roll_ang joint_pitch_ang joint_yaw_ang finger_length_1 finger_length_2 finger_length_3 finger_1_mass finger_2_mass finger_3_mass">
        <joint name="right_hand_finger_${number}_joint" type="revolute">
            <origin xyz="${joint_x_loc} ${joint_y_loc} ${joint_z_loc}" rpy="${joint_roll_ang} ${joint_pitch_ang} ${joint_yaw_ang}" />
            <parent link="${parent}"/>
            <child link="right_hand_finger_${prefix_1}_link" />
            <axis xyz="1 0 0"/>
            <limit effort ="30" lower="0" upper= "${M_PI/2}" velocity="0.5"/>
        </joint>

         <transmission name="right_hand_finger_${number}_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="right_hand_finger_${number}_joint" >
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_hand_finger_${number}_joint_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <link name="right_hand_finger_${prefix_1}_link">
            <visual>
                <origin xyz="0 -0.0045 ${finger_length_1/2}  " rpy="0 0 0" />
                <geometry>
                    <box size="${finger_width} ${finger_thickness} ${finger_length_1}"/>
                </geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${finger_length_1/2}" rpy="0 0 0 " />
                <geometry>
                     <box size="${finger_width} ${finger_thickness} ${finger_length_1}"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="${finger_1_mass}" w="${finger_width}" h="${finger_thickness}" d="${finger_length_1}" />
          </link>
        <gazebo reference="right_hand_finger_${prefix_1}_link">
            <material>Gazebo/Red</material>
            <gravity>true</gravity>
        </gazebo>

        <joint name = "right_hand_finger_${prefix_2}_joint" type = "revolute">
            <origin xyz = "0 -0.0045 ${finger_length_1}" rpy = "0 0 0" />
            <parent link  = "right_hand_finger_${prefix_1}_link" />
            <child link = "right_hand_finger_${prefix_2}_link" />
            <axis xyz = "1 0 0"/>
            <limit effort ="30" lower="0" upper= "${M_PI/2}" velocity="0.5"/>
        </joint>

        <transmission name="right_hand_finger_${prefix_2}_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
             <joint name="right_hand_finger_${prefix_2}_joint" >
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_hand_finger_${prefix_2}_joint_motor">
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <link name="right_hand_finger_${prefix_2}_link">
            <visual>
                <origin xyz="0 0 ${finger_length_2/2}  " rpy="0 0 0" />
                <geometry>
                    <box size="${finger_width} ${finger_thickness} ${finger_length_2}"/>
                </geometry>
                <material name="white"/>
            </visual>
        <collision>
                <origin xyz="0 0 ${finger_length_2/2}" rpy="0 0 0 " />
                <geometry>
                     <box size="${finger_width} ${finger_thickness} ${finger_length_2}"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="${finger_2_mass}" w="${finger_width}" h="${finger_thickness}" d="${finger_length_2}" />
          </link>
         <gazebo reference="right_hand_finger_${prefix_2}_link">
            <material>Gazebo/White</material>
            <gravity>true</gravity>
        </gazebo>

        <joint name = "right_hand_finger_${prefix_3}_joint" type = "revolute">
            <origin xyz = "0 0 ${finger_length_2}" rpy = "0 0 0" />
            <parent link  = "right_hand_finger_${prefix_2}_link" />
            <child link = "right_hand_finger_${prefix_3}_link" />
            <axis xyz = "1 0 0"/>
            <limit effort ="30" lower="0" upper= "${M_PI/2}" velocity="0.5"/>
        </joint>

        <transmission name="right_hand_finger_${prefix_3}_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="right_hand_finger_${prefix_3}_joint" >
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_hand_finger_${prefix_3}_joint_motor">
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <link name="right_hand_finger_${prefix_3}_link">
            <visual>
                <origin xyz="0 0 ${finger_length_3/2}  " rpy="0 0 0" />
                <geometry>
                    <box size="${finger_width} ${finger_thickness} ${finger_length_3}"/>
                </geometry>
                <material name="blue">
                  <color rgba="0.0 0.0 0.8 1.0"/>
                </material>
            </visual>
        <collision>
                <origin xyz="0 0 ${finger_length_3/2}" rpy="0 0 0 " />
                <geometry>
                     <box size="${finger_width} ${finger_thickness} ${finger_length_3}"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="${finger_3_mass}" w="${finger_width}" h="${finger_thickness}" d="${finger_length_3}" />
          </link>
      <gazebo reference="right_hand_finger_${prefix_3}_link">
            <material>Gazebo/Blue</material>
            <gravity>true</gravity>
      </gazebo>
    </xacro:macro>


   <link name = "right_base_link">
       <visual>
           <origin xyz = "-0.005 -0.005 0.0" rpy = "1.57 0 0" />
           <geometry>
               <box size="${base_link_x} ${base_link_y} ${base_link_z}" />
           </geometry>
           <material name="orange">
             <color rgba="1.0  0.55 0.0 1.0"/>
           </material>
        </visual>
        <collision>
                <origin xyz="-0.002 -0.011 0" rpy="1.57 0 0 " />
                <geometry>
                     <box size="${base_link_x} ${base_link_y} ${base_link_z}"/>
                </geometry>
            </collision>
         <xacro:box_inertial_matrix  m="${base_link_mass}" w="${base_link_x}" h="${base_link_y}" d="${base_link_z}" />
    </link>
   <gazebo reference="right_base_link">
            <material>Gazebo/Yellow</material>
            <gravity>true</gravity>
   </gazebo>

 <!-- Define base_hand_big_thunb -->

  <joint name = "right_base_hand_big_thumb_1" type = "revolute">
         <origin xyz = "-0.006 -0.0011 -0.02785" rpy = "0 0 0" />
         <parent link  = "right_base_link" />
         <child link = "right_hand_big_thumb_1" />
         <axis xyz = "0 0 1"/>
         <limit effort ="30" lower="${-M_PI/2}" upper= "0" velocity="0.5"/>
  </joint>

  <transmission name="right_base_hand_big_thumb_1_trans">
            <type>transmission_interface/SimpleTransmission</type>
             <joint name="right_base_hand_big_thumb_1" >
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_base_hand_big_thumb_1_joint_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

 <link name = "right_hand_big_thumb_1">
       <visual>
           <origin xyz = "0.010 0 0" rpy = "0 1.57 0" />
           <geometry>
               <cylinder radius = "0.005" length = "0.020"/>
           </geometry>
           <material name = "gray"/>
        </visual>
        <collision>
                <origin xyz="0.010 0 0" rpy="0 1.57 0 " />
                <geometry>
                      <cylinder radius = "0.005" length = "0.020"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="0.004304" r="0.005" h="0.020"  />
    </link>
    <gazebo reference="right_hand_big_thumb_1">
            <material>Gazebo/Grey</material>
            <gravity>true</gravity>
    </gazebo>

<joint name = "right_base_zhuanjie_1" type = "fixed">
         <origin xyz = "0.020 0 0" rpy = "0 -0.087222 0" />
         <parent link  = "right_hand_big_thumb_1" />
         <child link = "right_hand_zhuanjie_1" />
  </joint>

 <link name = "right_hand_zhuanjie_1">
       <visual>
           <origin xyz = "0.025 0 0" rpy = "0 0 0" />
           <geometry>
               <box size = "0.005 0.004 0.01"/>
           </geometry>
           <material name = "black"/>
        </visual>
        <collision>
                <origin xyz="0.025 0 0" rpy="0 0 0 " />
                <geometry>
                       <box size = "0.005 0.004 0.01"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="0.0008867" w="0.005" h="0.004" d="0.01"  />
    </link>
    <gazebo reference="right_hand_zhuanjie_1">
            <material>Gazebo/Black</material>
            <gravity>true</gravity>
    </gazebo>

<joint name = "right_base_zhuanjie_2" type = "fixed">
         <origin xyz = "0.005 0 0" rpy = "0 0 0" />
         <parent link  = "right_hand_zhuanjie_1" />
         <child link = "right_hand_zhuanjie_2" />
  </joint>

<link name = "right_hand_zhuanjie_2">
       <visual>
           <origin xyz = "0.02625 0.006 -0.011125" rpy = "0 0 0" />
           <geometry>
               <box size = "0.0525 0.0220 0.02225"/>
           </geometry>
           <material name = "black"/>
         </visual>
         <collision>
                <origin xyz="0.02625 0.006 -0.011125" rpy="0 0 0 " />
                <geometry>
                       <box size = "0.0525 0.0220 0.02225"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="0.0704" w="0.0525" h="0.0220" d="0.02225"  />
    </link>
    <gazebo reference="right_hand_zhuanjie_2">
            <material>Gazebo/Black</material>
            <gravity>true</gravity>
    </gazebo>


  <joint name = "right_base_hand_big_thumb_2" type = "revolute">
         <origin xyz = "0.0525 0.006 -0.0055" rpy = "0 0 0" />
         <parent link  = "right_hand_zhuanjie_2" />
         <child link = "right_hand_big_thumb_2" />
         <axis xyz = "0 1 0"/>
         <limit effort ="30" lower="${-M_PI/2}" upper= "0" velocity="0.5"/>
  </joint>

  <transmission name="right_base_hand_big_thumb_2_trans">
            <type>transmission_interface/SimpleTransmission</type>
           <joint name="right_base_hand_big_thumb_2" >
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_base_hand_big_thumb_2_joint_motor">
               <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

   <link name = "right_hand_big_thumb_2">
       <visual>
           <origin xyz = "0.024675 0 0" rpy = "0 0 0" />
           <geometry>
               <box size = "0.04935 0.022 0.011"/>
           </geometry>
           <material name = "white"/>
        </visual>
        <collision>
                <origin xyz="0.024675 0 0" rpy="0 0 0 " />
                <geometry>
                       <box size = "0.04935 0.022 0.011"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="0.038357" w="0.04935" h="0.022" d="0.011"  />
    </link>
    <gazebo reference="right_hand_big_thumb_2">
            <material>Gazebo/Red</material>
            <gravity>true</gravity>
    </gazebo>

  <link name = "right_hand_big_thumb_3">
       <visual>
           <origin xyz = "0.016275 0 0" rpy = "0 0 0"/>
           <geometry>
               <box size = "0.03255 0.022 0.011"/>
           </geometry>
           <material name="blue">
             <color rgba="0.0 0.0 0.8 1.0"/>
           </material>
        </visual>
       <collision>
                <origin xyz="0.016275 0 0" rpy="0 0 0 " />
                <geometry>
                       <box size = "0.03255 0.022 0.011"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix  m="0.027218" w="0.03255" h="0.022" d="0.011"/>
    </link>
    <gazebo reference="right_hand_big_thumb_3">
            <material>Gazebo/Green</material>
            <gravity>true</gravity>
    </gazebo>

  <joint name = "right_base_hand_big_thumb_3" type = "revolute">
         <origin xyz = "0.04935 0 0" rpy = "0 0 0" />
         <parent link  = "right_hand_big_thumb_2" />
         <child link = "right_hand_big_thumb_3" />
         <axis xyz = "0 1 0"/>
         <limit effort ="30" lower="${-M_PI/2}" upper= "0" velocity="0.5"/>
  </joint>

 <transmission name="right_base_hand_big_thumb_3_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="right_base_hand_big_thumb_3" >
                 <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_base_hand_big_thumb_3_joint_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

 <!-- shizhi -->
 <xacro:right_hand_finger parent="right_base_link" number="1" prefix_1 = "shizhidown" prefix_2 = "shizhimid" prefix_3 = "shizhitop" joint_x_loc="0.037613" joint_y_loc="-0.0025" joint_z_loc="0.045947" joint_roll_ang = "0" joint_pitch_ang = "0.06105556" joint_yaw_ang = "-0.05233333" finger_length_1 = "${finger_down}" finger_length_2 = "${finger_mid}" finger_length_3 = "${finger_top}" finger_1_mass="${finger_down_mass}" finger_2_mass="${finger_mid_mass}" finger_3_mass="${finger_top_mass}" />
 <!-- zhongzhi -->
 <xacro:right_hand_finger parent="right_base_link" number="2" prefix_1 = "zhongzhidown" prefix_2 = "zhongzhimid" prefix_3 = "zhongzhitop" joint_x_loc="0.01" joint_y_loc="0.0" joint_z_loc="0.05" joint_roll_ang = "0" joint_pitch_ang = "0" joint_yaw_ang = "0" finger_length_1 = "${finger_down}" finger_length_2 = "${finger_zhongzhi_mid}" finger_length_3 = "${finger_zhongzhi_top}" finger_1_mass="${finger_down_mass}"
finger_2_mass="${finger_zhongzhi_mid_mass}" finger_3_mass="${finger_zhongzhi_top_mass}"/>
 <!-- wumingzhi -->
<xacro:right_hand_finger parent="right_base_link" number="3" prefix_1 = "wumingzhidown" prefix_2 = "wumingzhimid" prefix_3 = "wumingzhitop" joint_x_loc="-0.017613" joint_y_loc="-0.0025" joint_z_loc="0.045947" joint_roll_ang = "0" joint_pitch_ang = "-0.06105556" joint_yaw_ang = "0.0523333" finger_length_1 = "${finger_down}" finger_length_2 = "${finger_mid}" finger_length_3 = "${finger_top}" finger_1_mass="${finger_down_mass}" finger_2_mass="${finger_mid_mass}" finger_3_mass="${finger_top_mass}"/>
 <!-- xiaozhi -->
<xacro:right_hand_finger parent="right_base_link" number="4" prefix_1 = "xiaozhidown" prefix_2 = "xiaozhimid" prefix_3 = "xiaozhitop" joint_x_loc="-0.044301" joint_y_loc="-0.0070" joint_z_loc="0.039976" joint_roll_ang = "0" joint_pitch_ang = "-0.13955556" joint_yaw_ang = "0.10466667" finger_length_1 = "${finger_down}" finger_length_2 = "${finger_mid}" finger_length_3 = "${finger_top}" finger_1_mass="${finger_down_mass}" finger_2_mass="${finger_mid_mass}" finger_3_mass="${finger_top_mass}"/>

<!--ros_control-->

</xacro:macro>
</robot>
